import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import Image from "next/image";
import Menu from "@/ui/Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex">
      {/* LEFT */}
      <div className="">
        <Link href="/">
          <Image src="" alt="Logo" width={32} height={32} />
        </Link>
        <Menu />
      </div>
      {/* RIGHT */}
      <div>
        
      </div>
    </div>
  );
}
